Home
bookloverbabe/acebook-mern-fire_team pull request #10
Opened 2023-05-16 14:20 UTC by robinvuy

Home Page complete with hyperlinks to direct to /login and /signup pages. Cypress tests passing. CSS inconsistent and may need further tweaking to match rest of Acebook.

2023-05-16 17:47 UTC, natashabuckham requested changes

2023-05-16 17:47 UTC, natashabuckham commented on frontend/src/components/app/App.js
could we pass the useNavigate prop in the Home route so that if the user visits '/' when they are already logged in then they are redirected to '/posts'?

2023-05-16 17:47 UTC, natashabuckham commented on package.json
I think an extra line has slipped in here which we don't need :)

2023-05-16 17:47 UTC, natashabuckham commented on frontend/src/components/app/App.js
This could use Jon's useContext to see if user is logged in

2023-05-18 13:48 UTC, robinvuy commented on package.json
Thanks Natasha, I've removed the duplicate line :)

2023-05-18 13:49 UTC, robinvuy commented on frontend/src/components/app/App.js
Ive passed the useNavigate prop in the Home route, but useContext might not be needed if this home page is used to be an "about page"

2023-05-18 15:41 UTC, natashabuckham approved these changes

2023-05-19 09:22 UTC, merged